apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-airbrake
data:
  AIRBRAKE_PROJECT_ID: {{ .Values.AIRBRAKE_PROJECT_ID | b64enc }}
  AIRBRAKE_PROJECT_KEY: {{ .Values.AIRBRAKE_PROJECT_KEY | b64enc }}
  AIRBRAKE_ENVIRONMENT: {{ .Values.AIRBRAKE_ENVIRONMENT | b64enc }}