name: "Deploy"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number"
        required: true
      environment:
        description: "Environment"
        required: true
jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: tags/v${{ github.event.inputs.version }}
      - name: Digital Ocean Authenticate
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: roman-numeral
      - name: Deploy Helm Chart
        run: helm upgrade ${HELM_NAME} --version=${VERSION} --set-string AIRBRAKE_PROJECT_ID=${AIRBRAKE_PROJECT_ID} --set-string AIRBRAKE_PROJECT_KEY=${AIRBRAKE_PROJECT_KEY} --set-string AIRBRAKE_ENVIRONMENT=${AIRBRAKE_ENVIRONMENT} --set-string image.tag=${VERSION} ./helm
        env:
          VERSION: ${{ github.event.inputs.version }}
          AIRBRAKE_PROJECT_ID: ${{secrets.AIRBRAKE_PROJECT_ID}}
          AIRBRAKE_PROJECT_KEY: ${{secrets.AIRBRAKE_PROJECT_KEY}}
          AIRBRAKE_ENVIRONMENT: ${{ github.event.inputs.environment }}
          HELM_NAME: ${{ github.event.inputs.environment }}
      - name: Airbrake Deploy Push
        uses: mtchavez/airbrake-deploy@v1
        with:
          project-id: ${{ secrets.AIRBRAKE_PROJECT_ID }}
          project-key: ${{ secrets.AIRBRAKE_PROJECT_KEY }}
          environment: ${{ github.event.inputs.environment }}
          repository: https://github.com${{ github.repo }}
          revision: ${{ github.sha }}
          user: ${{ github.actor }}
