name: "Release"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number"
        required: true
      environment:
        description: "Environment"
        required: true
jobs:
jobs:
  helm-install:
    runs-on: ubuntu-latest
    needs: docker-release
    steps:
      - uses: actions/checkout@v1
        with:
          ref: tags/v${{ github.event.inputs.version }}
      - name: Digital Ocean Authenticate
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: roman-numeral
      - name: Deploy Helm Chart
        run: npm run deploy:helm
        env:
          VERSION: ${{ github.event.inputs.version }}
          AIRBRAKE_PROJECT_ID: ${{secrets.AIRBRAKE_PROJECT_ID}}
          AIRBRAKE_PROJECT_KEY: ${{secrets.AIRBRAKE_PROJECT_KEY}}
          AIRBRAKE_ENVIRONMENT: ${{ github.event.inputs.environment }}
          HELM_NAME: ${{ github.event.inputs.environment }}
      - name: Airbrake Deploy Push
        uses: actions/airbrake-deploy-github-action@v1
        with:
          project-id: ${{ secrets.AIRBRAKE_PROJECT_ID }}
          project-key: ${{ secret.AIRBRAKE_PROJECT_KEY }}
          environment: ${{ github.event.inputs.environment }}
          repository: https://github.com${{ github.repo }}
          revision: ${{ github.sha }}
          user: ${{ github.actor }}
