name: "Release"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number"
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          token: ${{ secrets.GH_PAT }}
      - run: npm ci
      - run: npm test
        env:
          AIRBRAKE_PROJECT_ID: ${{secrets.AIRBRAKE_PROJECT_ID}}
          AIRBRAKE_PROJECT_KEY: ${{secrets.AIRBRAKE_PROJECT_KEY}}
          AIRBRAKE_ENVIRONMENT: ${{secrets.AIRBRAKE_ENVIRONMENT}}
      - run: git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
      - run: npm version ${{ github.event.inputs.version }}
      - run: git tag -a ${{ github.event.inputs.version }} -m "Releasing ${{ github.event.inputs.version }}"
      - run: git push --all
      - run: npm run build:docker
        env:
          VERSION: ${{ github.event.inputs.version }}
      - run: echo ${{ secrets.GH_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - run: npm run release:docker
        env:
          VERSION: ${{ github.event.inputs.version }}
