name: "Release"
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number"
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NodeJS dependencies
        run: npm ci
      - name: NodeJS Tests
        run: npm test
        env:
          AIRBRAKE_PROJECT_ID: ${{secrets.AIRBRAKE_PROJECT_ID}}
          AIRBRAKE_PROJECT_KEY: ${{secrets.AIRBRAKE_PROJECT_KEY}}
          AIRBRAKE_ENVIRONMENT: ${{secrets.AIRBRAKE_ENVIRONMENT}}
  version:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        name: Checking out code
        env:
          token: ${{ secrets.GH_PAT }}
      - name: Tagging release ${VERSION}
        run: |
          npm version ${VERSION}
          git config --global user.name "Github Actions"
          git config --global user.email github-actions@github.com
          git push origin HEAD:main --tags
        env:
          VERSION: ${{ github.event.inputs.version }}
          token: ${{ secrets.GH_PAT }}
  docker-release:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - uses: actions/checkout@v1
      - name: Docker build
        run: npm run build:docker
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Login to Github Container Registry
        run: echo ${GITHUB_TOKEN} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Push release to Github Container Registry
        run: npm run release:docker
        env:
          VERSION: ${{ github.event.inputs.version }}
